[live]
  poster = "/cloud.png"
  title = "Nebula Graph Cloud Service 公测中"
  text = "Nebula Graph DBaaS 服务——Nebula Graph Cloud Service 已上线，现处于公测阶段，来试试这个免部署让你专注数据，深挖数据背后价值的产品吧~ "
  link = "https://cloud.nebula-graph.com.cn/"
  btnText = "免费试用"