contentDir = "content/en"
[params]
  # NewsRoom section
  [params.newsRoom]
    title="Nebula Graph Media Coverage"
    description="Media coverage on the Nebula Graph database, ranging from fundraising, feature updates, product releases, to community events. "
  # News section
  [params.news]
      pic = "download.png"
      downloadLink = "/file/NebulaGraphMediaKit.zip"
      title="News Coverage"
      content1= "• Company logo"
      content2= "• Founder headshot"
      link = "/news"
      readMore = "Read More >>"
      newsTitle="Nebula Graph Media Coverage | News Coverage"
      newsDescription="News coverage on the Nebula Graph database from external media platforms like TechCrunch."
      [[params.news.list]]
        pic = "feature1.png"
        title = "Nebula Graph Debuts for Big Data Analytics Discovery"
        link = "https://www.datanami.com/this-just-in/nebula-graph-debuts-for-big-data-analytics-discovery/"
        date = "June 29, 2020"
        source = "Datanami"
        readMore = "Read More >>"
        Description = "Nebula Graph is now commercially available as the only database that can store and process billions of data points with trillions of relational connections in a shared-nothing distributed architecture for the industry’s best business continuity."

      [[params.news.list]]
        pic = "feature1.png"
        title = "Nebula Graph is now available from VEsoft"
        link = "https://www.kmworld.com/Articles/News/News/Nebula-Graph-is-now-available-from-VEsoft-141573.aspx"
        date = "June 29, 2020"
        source = "KMWorld"
        readMore = "Read More >>"
        Description = "Nebula Graph is now available, providing a graph database that can store and process billions of data points with trillions of relational connections."

      [[params.news.list]]
        pic = "feature1.png"
        title = "VESoft raises $8M to meet China’s growing need for graph databases"
        link = "https://techcrunch.com/2020/06/15/vesoft-china-graph-database-8m-funding/"
        date = "June 15, 2020"
        source = "TechCrunch"
        readMore = "Read More >>"
        Description = "VEsoft raises $8M to meet China’s growing need for graph databases. The new capital will allow the startup to develop products and expand to markets in North America, Europe and other parts of Asia."

      [[params.news.list]]
        pic = "feature1.png"
        title = "Nebula Graph Database Raises $8M in Series Pre-A Funding"
        link = "https://www.enterpriseai.news/2020/06/15/nebula-graph-database-raises-8m-in-series-pre-a-funding/"
        date = "June 15, 2020"
        source = "EnterpriseAI"
        Description = "VEsoft Inc., the developer of the Nebula Graph database, announced it raised $8M in a series pre-A funding round. The lead investor is Redpoint China Ventures. "

      [[params.news.list]]
        pic = "feature1.png"
        title = "Nebula Graph Joins Database Race"
        link = "https://www.datanami.com/2020/06/15/nebula-graph-joins-database-race/"
        date = "June 15, 2020"
        source = "Datanami"
        Description = "As the open source Nebula Graph database moves closer to commercial availability, the technology’s developer has announced an early funding round led by several Chinese investors."
      
      [[params.news.list]]
        pic = "feature1.png"
        title = "VEsoft receives $8 million in latest funding round to expand the Nebula Graph database"
        link = "https://www.kmworld.com/Articles/News/News/VEsoft-receives-%248-million-in-latest-funding-round-to-expand-the-Nebula-Graph-database-141322.aspx"
        date = "June 15, 2020"
        source = "KMWorld"
        Description = "VEsoft Inc., the developer of the Nebula Graph database, has raised $8 million in a series pre-A funding round, enabling the company to perform additional product management and expand its footprint."
      
      [[params.news.list]]
        pic = "feature1.png"
        title = "VESoft raises $8M to meet China's growing need for graph databases"
        link = "https://news.yahoo.com/vesoft-raises-8m-meet-chinas-120044029.html"
        date = "June 15, 2020"
        source = "Yahoo! News"
        Description = "VESoft is ready for further growth after closing an $8 million funding round led by Redpoint China Ventures, an investment firm launched by Silicon Valley-based Redpoint Ventures in 2005."
