###  导航栏提示框

popupText= "Nebula Graph Cloud Service 上线啦，一键部署免安装"
popupLinkText= "免费试用"
popupLink= "https://cloud.nebula-graph.com.cn/"
popupClick="gtag('event', 'Link Click', { event_category: 'Engagement', event_label: 'Banner Ad - Nebula Graph Cloud Service'})"

### 帮助对话提示框
helpDialog="欢迎来到 Nebula Graph！有什么可以帮您的吗?"