baseurl = "https://nebula-graph.com.cn"
title = "Nebula Graph 开源分布式图数据库"
theme = "creative"
googleAnalytics = ""
DefaultContentLanguage = "cn"
defaultContentLanguageInSubdir = false

[languages]
################ init language Config ################
  [languages.default]
    contentDir = "content/cn"
