name:
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Github Action
      uses: actions/checkout@master

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.65.3'

    - name: Build
      run: hugo --environment=english --minify -d nebula-website

    - name: Remove resource about chinese
      run: rm -rf ./nebula-website/cn/

    - name: Compress
      run: tar -czf site.tar.gz nebula-website

    - name: Transfer
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          source: site.tar.gz 
          target: /home/vesoft

    - name: UnCompress
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}
        script: tar -xzvf /home/vesoft/site.tar.gz -C /home/vesoft/